version: '3.7'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: reverse-proxy
    restart: unless-stopped
    tty: true
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/logs:/var/log/nginx/
    networks:
      - sabaimotors

networks:
  sabaimotors:
    driver: bridge
